[package]
name = "vagga"
version = "0.4.1"
authors = ["Paul Colomiets"]

[dependencies]
libc = "*"
nix = "*"
shaman = "*"
rand = "*"
argparse = "0.2.1"
quire = "0.1.5"
rustc-serialize = "*"
log = "*"
time = "*"
env_logger = "*"
url = "*"
unshare = "0.1.7"
signal = "0.1.3"
quick-error = "0.1.4"
mopa = "0.2.0"
anymap = "0.11.1"
matches = "0.1.2"
regex = "0.1.41"
scan_dir = "0.3.1"

[[bin]]
name = "vagga"
path = "src/main.rs"
